services:
  db:
    image: postgres:16-alpine
    container_name: sghss_db
    environment:
      POSTGRES_DB: sghss_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - sghss_novo_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sghss_backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sghss_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}

volumes:
  sghss_novo_data: