spring.application.name=sghss
spring.datasource.url=jdbc:postgresql://localhost:5432/sghss_db
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update